spring.application.name=gymtracker

spring.datasource.url=jdbc:h2:file:./gymtracker-db
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.hibernate.ddl-auto=update

server.port=${PORT:8080}

