spring.application.name=gymtracker
server.port=${PORT:8080}

# H2 para desarrollo local
spring.datasource.url=jdbc:h2:file:./gymtracker-db
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

jwt.secret=miClaveSecretaSuperSeguraParaJWTGymTracker2025