# PostgreSQL para producción
spring.datasource.url=jdbc:postgresql://aws-1-us-west-2.pooler.supabase.com:5432/postgres?user=postgres.vujlnylsslyvdesxaedm&password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update